[build]
  command = "mkdir -p functions/backend && cp backend/main.py functions/backend/__init__.py && cp backend/sei_scraper.py functions/backend/sei_scraper.py && pip install -r backend/requirements.txt -t functions/backend"
  functions = "functions"
  publish = "."

[functions]
  external_node_modules = ["python-multipart"]

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200